name: quiz_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  kartal: ^3.5.0
  google_fonts: 6.1.0
  responsive_sizer: ^3.3.0+1
  riverpod: ^2.5.1
  wolt_modal_sheet: ^0.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
